// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MindsageWeb.Tests.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class Show_Lesson_CommentsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Show_Lesson_Comments.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Show_Lesson_Comments", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Show_Lesson_Comments")))
            {
                MindsageWeb.Tests.Specs.Show_Lesson_CommentsFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("Initialize mocking data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.And("System have ClassCalendar collection with JSON format are", @"[
    {
        ""id"": ""CCalendar01"",
        ""BeginDate"": ""2/1/2016"",
        ""ClassRoomId"": ""CR01"",
        ""LessonCalendars"":
        [
            {
                ""Id"": ""LC01"",
                ""LessonId"": ""L01"",
                ""BeginDate"": ""2/1/2016"",
                ""LessonCatalogId"": ""LCatalog01""
            },
            {
                ""Id"": ""LC02"",
                ""LessonId"": ""L02"",
                ""BeginDate"": ""2/8/2016"",
                ""LessonCatalogId"": ""LCatalog02""
            },
            {
                ""Id"": ""LC03"",
                ""LessonId"": ""L03"",
                ""BeginDate"": ""2/15/2016"",
                ""LessonCatalogId"": ""LCatalog03""
            },
        ]
    },
]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
    testRunner.And("System have Subscription collection with JSON format are", "[\r\n    {\r\n        \"id\": \"S01\",\r\n        \"UserProfileId\": \"sakul@mindsage.com\",\r\n " +
                    "       \"ClassRoomId\": \"CR01\",\r\n        \"Role\": \"Teacher\"\r\n    },\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
    testRunner.And("System have CourseFriend collection with JSON format are", "[\r\n    {\r\n        \"id\": \"CourseFriend01\",\r\n        \"UserProfileId\": \"sakul@mindsa" +
                    "ge.com\",\r\n        \"ClassRoomId\": \"CR01\",\r\n        \"FriendWith\":\r\n        [\r\n    " +
                    "        \"earn@mindsage.com\"\r\n        ]\r\n    }\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
    testRunner.And("System have Comment collection with JSON format are", "[\r\n    {\r\n        \"id\": \"Comment01\",\r\n        \"ClassRoomId\": \"CR01\",\r\n        \"Cr" +
                    "eatedByUserProfileId\": \"sakul@mindsage.com\",\r\n        \"Description\": \"Msg01\",\r\n " +
                    "       \"TotalLikes\": 0,\r\n        \"LessonId\": \"L01\",\r\n\"CreatedDate\": \"2/1/2016 01" +
                    ":00 am\",\r\n\"Discussions\": []\r\n    },\r\n    {\r\n        \"id\": \"Comment02\",\r\n        " +
                    "\"ClassRoomId\": \"CR01\",\r\n        \"CreatedByUserProfileId\": \"sakul@mindsage.com\",\r" +
                    "\n        \"Description\": \"Msg02\",\r\n        \"TotalLikes\": 5,\r\n        \"LessonId\": " +
                    "\"L02\",\r\n\"CreatedDate\": \"2/1/2016 02:00 am\",\r\n        \"Discussions\":\r\n        [\r\n" +
                    "            {\r\n                \"Id\": \"DiscussionId01\",\r\n                \"Descrip" +
                    "tion\": \"Discussion01\",\r\n                \"TotalLikes\": 100,\r\n                \"Cre" +
                    "atedByUserProfileId\": \"sakul@mindsage.com\",\r\n\t\"CreatedDate\": \"2/1/2016 02:01 am\"" +
                    ",\r\n            }\r\n        ]\r\n    },\r\n    {\r\n        \"id\": \"Comment03\",\r\n        " +
                    "\"ClassRoomId\": \"CR01\",\r\n        \"CreatedByUserProfileId\": \"earn@mindsage.com\",\r\n" +
                    "        \"Description\": \"Msg03\",\r\n        \"TotalLikes\": 10,\r\n        \"LessonId\": " +
                    "\"L02\",\r\n\"CreatedDate\": \"2/1/2016 03:00 am\",\r\n        \"Discussions\":\r\n        [\r\n" +
                    "            {\r\n                \"Id\": \"DiscussionId02\",\r\n                \"Descrip" +
                    "tion\": \"Discussion02\",\r\n                \"TotalLikes\": 200,\r\n                \"Cre" +
                    "atedByUserProfileId\": \"someone@mindsage.com\",\r\n\t\"CreatedDate\": \"2/1/2016 03:01 a" +
                    "m\",\r\n            },\r\n            {\r\n                \"Id\": \"DiscussionId03\",\r\n   " +
                    "             \"Description\": \"Discussion03\",\r\n                \"TotalLikes\": 300,\r" +
                    "\n                \"CreatedByUserProfileId\": \"sakul@mindsage.com\",\r\n\t\"CreatedDate\"" +
                    ": \"2/1/2016 03:02 am\",\r\n            }\r\n        ]\r\n    },\r\n    {\r\n        \"id\": \"" +
                    "Comment04\",\r\n        \"ClassRoomId\": \"CR01\",\r\n        \"CreatedByUserProfileId\": \"" +
                    "someone@mindsage.com\",\r\n        \"Description\": \"Msg04\",\r\n        \"TotalLikes\": 1" +
                    "5,\r\n        \"LessonId\": \"L02\",\r\n\"CreatedDate\": \"2/1/2016 04:00 am\",\r\n        \"Di" +
                    "scussions\":\r\n        [\r\n            {\r\n                \"Id\": \"DiscussionId04\",\r\n" +
                    "                \"Description\": \"Discussion04\",\r\n                \"TotalLikes\": 40" +
                    "0,\r\n\t\"CreatedByUserProfileId\": \"someone@mindsage.com\",\r\n\t\"CreatedDate\": \"2/1/201" +
                    "6 04:01 am\",\r\n            }\r\n        ]\r\n    },\r\n]", ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("User request lesson\'s comments and their discussions Then system send the lesson\'" +
            "s comments and their discussions back")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Show_Lesson_Comments")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mock")]
        public virtual void UserRequestLessonSCommentsAndTheirDiscussionsThenSystemSendTheLessonSCommentsAndTheirDiscussionsBack()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User request lesson\'s comments and their discussions Then system send the lesson\'" +
                    "s comments and their discussions back", new string[] {
                        "mock"});
#line 145
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 146
    testRunner.Given("Today is \'2/8/2016 00:00 am\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 147
    testRunner.When("UserProfile \'sakul@mindsage.com\' request comment & discussion from the lesson \'L0" +
                    "2\' of ClassRoom: \'CR01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 148
    testRunner.Then("System send lesson\'s comment and their discussions with JSON format are", @"[
{
        ""id"": ""Comment03"",
        ""ClassRoomId"": ""CR01"",
        ""CreatedByUserProfileId"": ""earn@mindsage.com"",
        ""Description"": ""Msg03"",
        ""TotalLikes"": 10,
        ""LessonId"": ""L02"",
""CreatedDate"": ""2/1/2016 03:00 am"",
        ""Discussions"":
        [
{
                ""Id"": ""DiscussionId03"",
                ""Description"": ""Discussion03"",
                ""TotalLikes"": 300,
                ""CreatedByUserProfileId"": ""sakul@mindsage.com"",
	""CreatedDate"": ""2/1/2016 03:02 am"",
            },
            {
                ""Id"": ""DiscussionId02"",
                ""Description"": ""Discussion02"",
                ""TotalLikes"": 200,
                ""CreatedByUserProfileId"": ""someone@mindsage.com"",
	""CreatedDate"": ""2/1/2016 03:01 am"",
            },
        ]
    },
    {
        ""id"": ""Comment02"",
        ""ClassRoomId"": ""CR01"",
        ""CreatedByUserProfileId"": ""sakul@mindsage.com"",
        ""Description"": ""Msg02"",
        ""TotalLikes"": 5,
        ""LessonId"": ""L02"",
""CreatedDate"": ""2/1/2016 02:00 am"",
        ""Discussions"":
        [
            {
                ""Id"": ""DiscussionId01"",
                ""Description"": ""Discussion01"",
                ""TotalLikes"": 100,
                ""CreatedByUserProfileId"": ""sakul@mindsage.com"",
	""CreatedDate"": ""2/1/2016 02:01 am"",
            }
        ]
    },
]", ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
